<?php

namespace Database\Seeders;

use App\Models\MedicalCertificate;
use App\Models\PatientRecord;
use App\Models\Referral;
use Illuminate\Database\Seeder;

class SampleDataSeeder extends Seeder
{
    /**
     * Seed representative records for demo and testing.
     */
    public function run(): void
    {
        foreach ($this->medicalCertificates() as $certificate) {
            MedicalCertificate::query()->firstOrCreate(
                ['mc_no' => $certificate['mc_no']],
                $certificate
            );
        }

        foreach ($this->referrals() as $referral) {
            Referral::query()->firstOrCreate(
                [
                    'patient_name' => $referral['patient_name'],
                    'referral_date' => $referral['referral_date'],
                ],
                $referral
            );
        }

        foreach ($this->patientRecords() as $record) {
            PatientRecord::query()->firstOrCreate(
                [
                    'full_name' => $record['full_name'],
                    'visit_date' => $record['visit_date'],
                    'module_type' => $record['module_type'],
                ],
                $record
            );
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function medicalCertificates(): array
    {
        return [
            [
                'name' => 'Juan Miguel Reyes',
                'age' => 21,
                'gender' => 'Male',
                'civil_status' => 'Single',
                'address' => 'Brgy. San Pedro, Puerto Princesa City, Palawan',
                'examination_date' => '2026-03-01',
                'reason' => 'Pre-employment medical examination for internship',
                'findings_fit' => true,
                'findings_impression' => false,
                'impression_text' => null,
                'advice' => 'Fit to work. Maintain adequate rest and hydration.',
                'receipt_no' => 'OR-2026-001',
                'date_issued' => '2026-03-01',
                'mc_no' => 'MC-2026-001',
            ],
            [
                'name' => 'Maria Clara Santos',
                'age' => 34,
                'gender' => 'Female',
                'civil_status' => 'Married',
                'address' => 'Brgy. Sta. Monica, Puerto Princesa City, Palawan',
                'examination_date' => '2026-03-05',
                'reason' => 'Annual physical examination',
                'findings_fit' => false,
                'findings_impression' => true,
                'impression_text' => 'Mild hypertension noted. Blood pressure 145/92 mmHg.',
                'advice' => 'Follow up with physician in 2 weeks. Reduce salt intake and monitor BP daily.',
                'receipt_no' => 'OR-2026-002',
                'date_issued' => '2026-03-05',
                'mc_no' => 'MC-2026-002',
            ],
            [
                'name' => 'Paolo Enrique Dela Cruz',
                'age' => 23,
                'gender' => 'Male',
                'civil_status' => 'Single',
                'address' => 'Brgy. Sicsican, Puerto Princesa City, Palawan',
                'examination_date' => '2026-03-15',
                'reason' => 'OJT medical clearance',
                'findings_fit' => true,
                'findings_impression' => false,
                'impression_text' => null,
                'advice' => 'Fit for on-the-job training. Continue regular exercise.',
                'receipt_no' => 'OR-2026-003',
                'date_issued' => '2026-03-15',
                'mc_no' => 'MC-2026-003',
            ],
            [
                'name' => 'Sofia Isabel Ramirez',
                'age' => 28,
                'gender' => 'Female',
                'civil_status' => 'Married',
                'address' => 'Brgy. San Jose, Puerto Princesa City, Palawan',
                'examination_date' => '2026-03-18',
                'reason' => 'Scholarship medical requirement',
                'findings_fit' => true,
                'findings_impression' => false,
                'impression_text' => null,
                'advice' => 'Physically fit. No activity restrictions.',
                'receipt_no' => 'OR-2026-004',
                'date_issued' => '2026-03-18',
                'mc_no' => 'MC-2026-004',
            ],
            [
                'name' => 'Roberto Luis Fernandez',
                'age' => 41,
                'gender' => 'Male',
                'civil_status' => 'Married',
                'address' => 'Brgy. Tiniguiban, Puerto Princesa City, Palawan',
                'examination_date' => '2026-03-20',
                'reason' => 'Faculty annual physical examination',
                'findings_fit' => false,
                'findings_impression' => true,
                'impression_text' => 'Elevated fasting blood sugar at 126 mg/dL. BMI 28.4.',
                'advice' => 'Dietary modification and repeat FBS in 2 weeks. Refer to internist if still elevated.',
                'receipt_no' => 'OR-2026-005',
                'date_issued' => '2026-03-20',
                'mc_no' => 'MC-2026-005',
            ],
            [
                'name' => 'Camille Joy Navarro',
                'age' => 19,
                'gender' => 'Female',
                'civil_status' => 'Single',
                'address' => 'Brgy. Bancao-Bancao, Puerto Princesa City, Palawan',
                'examination_date' => '2026-03-22',
                'reason' => 'Varsity sports medical clearance',
                'findings_fit' => true,
                'findings_impression' => false,
                'impression_text' => null,
                'advice' => 'Cleared for athletic participation. Stretch properly before training.',
                'receipt_no' => 'OR-2026-006',
                'date_issued' => '2026-03-22',
                'mc_no' => 'MC-2026-006',
            ],
            [
                'name' => 'Eduardo Santos Jr.',
                'age' => 45,
                'gender' => 'Male',
                'civil_status' => 'Married',
                'address' => 'Brgy. San Miguel, Puerto Princesa City, Palawan',
                'examination_date' => '2026-03-25',
                'reason' => 'Pre-employment medical examination for staff hiring',
                'findings_fit' => false,
                'findings_impression' => true,
                'impression_text' => 'Dyslipidemia. Total cholesterol 248 mg/dL.',
                'advice' => 'Low-fat diet, daily walking, and lipid profile follow-up after 1 month.',
                'receipt_no' => 'OR-2026-007',
                'date_issued' => '2026-03-25',
                'mc_no' => 'MC-2026-007',
            ],
            [
                'name' => 'Hannah Mae Alcantara',
                'age' => 20,
                'gender' => 'Female',
                'civil_status' => 'Single',
                'address' => 'Brgy. Irawan, Puerto Princesa City, Palawan',
                'examination_date' => '2026-04-02',
                'reason' => 'Board examination medical certificate',
                'findings_fit' => true,
                'findings_impression' => false,
                'impression_text' => null,
                'advice' => 'Fit to take the licensure examination.',
                'receipt_no' => 'OR-2026-008',
                'date_issued' => '2026-04-02',
                'mc_no' => 'MC-2026-008',
            ],
            [
                'name' => 'Kenneth Paul Bautista',
                'age' => 26,
                'gender' => 'Male',
                'civil_status' => 'Single',
                'address' => 'Brgy. Mandaragat, Puerto Princesa City, Palawan',
                'examination_date' => '2026-04-06',
                'reason' => 'Internship medical examination',
                'findings_fit' => true,
                'findings_impression' => false,
                'impression_text' => null,
                'advice' => 'Fit for hospital internship. Complete remaining immunizations as advised.',
                'receipt_no' => 'OR-2026-009',
                'date_issued' => '2026-04-06',
                'mc_no' => 'MC-2026-009',
            ],
        ];
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function referrals(): array
    {
        return [
            [
                'hospital_clinic' => 'Ospital ng Palawan',
                'referral_date' => '2026-03-10',
                'patient_name' => 'Carlo Mendoza',
                'patient_age' => 19,
                'patient_sex' => 'MALE',
                'patient_type_student' => true,
                'patient_address' => 'Brgy. Tagumpay, Puerto Princesa City, Palawan',
                'case_summary' => 'Persistent cough and low-grade fever for 5 days. Chest clear on auscultation.',
                'reason_for_referral' => 'For chest X-ray and further pulmonary evaluation.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
            [
                'hospital_clinic' => 'Palawan Dental Center',
                'referral_date' => '2026-03-12',
                'patient_name' => 'Liza Mae Torres',
                'patient_age' => 22,
                'patient_sex' => 'FEMALE',
                'patient_type_student' => true,
                'patient_address' => 'Brgy. San Manuel, Puerto Princesa City, Palawan',
                'case_summary' => 'Severe tooth pain on lower right molar. Visible caries on tooth #46.',
                'reason_for_referral' => 'For possible extraction or root canal treatment.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
            [
                'hospital_clinic' => 'Ospital ng Palawan',
                'referral_date' => '2026-03-16',
                'patient_name' => 'Miguel Angelo Ramos',
                'patient_age' => 20,
                'patient_sex' => 'MALE',
                'patient_type_student' => true,
                'patient_address' => 'Brgy. San Pedro, Puerto Princesa City, Palawan',
                'case_summary' => 'High-grade fever, headache, and muscle pain for 3 days. Positive tourniquet test.',
                'reason_for_referral' => 'For CBC with platelet count and dengue NS1/IgM work-up.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
            [
                'hospital_clinic' => 'Palawan Baptist Hospital',
                'referral_date' => '2026-03-19',
                'patient_name' => 'Patricia Ann Go',
                'patient_age' => 35,
                'patient_sex' => 'FEMALE',
                'patient_type_faculty' => true,
                'patient_address' => 'Brgy. Sta. Monica, Puerto Princesa City, Palawan',
                'case_summary' => 'Palpable anterior neck mass, slowly enlarging for 2 months. Euthyroid on exam.',
                'reason_for_referral' => 'For thyroid ultrasound and endocrinology consult.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
            [
                'hospital_clinic' => 'Puerto Princesa Adventist Hospital',
                'referral_date' => '2026-03-24',
                'patient_name' => 'Joshua Emmanuel Cruz',
                'patient_age' => 18,
                'patient_sex' => 'MALE',
                'patient_type_student' => true,
                'patient_address' => 'Brgy. San Jose, Puerto Princesa City, Palawan',
                'case_summary' => 'Deep laceration on the left forearm after a fall from a bicycle. Bleeding controlled.',
                'reason_for_referral' => 'For wound exploration, suturing, and tetanus prophylaxis.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
            [
                'hospital_clinic' => 'ACE Medical Center Palawan',
                'referral_date' => '2026-03-28',
                'patient_name' => 'Rhea Nicole Valdez',
                'patient_age' => 24,
                'patient_sex' => 'FEMALE',
                'patient_type_student' => true,
                'patient_address' => 'Brgy. Sicsican, Puerto Princesa City, Palawan',
                'case_summary' => 'Dysuria, frequency, and left flank pain for 2 days. Febrile at 38.4°C.',
                'reason_for_referral' => 'For urinalysis, urine culture, and possible pyelonephritis management.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
            [
                'hospital_clinic' => 'Ospital ng Palawan',
                'referral_date' => '2026-04-01',
                'patient_name' => 'Benjamin Torres',
                'patient_age' => 52,
                'patient_sex' => 'MALE',
                'patient_type_staff' => true,
                'patient_address' => 'Brgy. Tiniguiban, Puerto Princesa City, Palawan',
                'case_summary' => 'Intermittent chest tightness radiating to the left arm. BP 158/98 mmHg.',
                'reason_for_referral' => 'For 12-lead ECG, cardiac enzymes, and emergency evaluation.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
            [
                'hospital_clinic' => 'Palawan Eye Center',
                'referral_date' => '2026-04-04',
                'patient_name' => 'Andrea Mae Lim',
                'patient_age' => 21,
                'patient_sex' => 'FEMALE',
                'patient_type_student' => true,
                'patient_address' => 'Brgy. Bancao-Bancao, Puerto Princesa City, Palawan',
                'case_summary' => 'Progressive blurring of vision for 3 weeks, worse at night. No eye trauma.',
                'reason_for_referral' => 'For visual acuity testing and ophthalmology evaluation.',
                'signature_name' => 'Dr. Ana Patricia Cruz',
                'designation' => 'University Physician',
            ],
        ];
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function patientRecords(): array
    {
        return [
            [
                'module_type' => 'health',
                'patient_type_id' => '1',
                'student_id' => '2022-CS-0142',
                'full_name' => 'Angela Rose Villanueva',
                'gender' => 'Female',
                'age' => 20,
                'marital_status' => 'Single',
                'religion' => 'Roman Catholic',
                'is_minor' => 'No',
                'phone_number' => '09171234567',
                'address' => 'Brgy. San Miguel, Puerto Princesa City, Palawan',
                'department_id' => '1',
                'visit_date' => '2026-03-08',
                'case_type_id' => '3',
                'diagnosis' => 'Acute upper respiratory tract infection',
                'treatment' => 'Paracetamol 500mg q6h PRN, increased fluid intake, rest for 3 days',
                'subjective' => 'Sore throat and runny nose for 2 days',
                'objectives' => 'Temp 37.8°C, pharyngeal erythema, no lung crackles',
                'diagnostics' => 'Clinical diagnosis',
                'assessment' => 'Mild URTI, likely viral',
                'plan' => 'Symptomatic treatment, return if fever persists beyond 3 days',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
            [
                'module_type' => 'health',
                'patient_type_id' => '1',
                'student_id' => '2023-ENG-0088',
                'full_name' => 'Mark Anthony Perez',
                'gender' => 'Male',
                'age' => 21,
                'marital_status' => 'Single',
                'religion' => 'Roman Catholic',
                'is_minor' => 'No',
                'phone_number' => '09181239876',
                'address' => 'Brgy. San Pedro, Puerto Princesa City, Palawan',
                'department_id' => '2',
                'visit_date' => '2026-03-14',
                'case_type_id' => '9',
                'diagnosis' => 'Acute gastritis',
                'treatment' => 'Omeprazole 40mg once daily for 7 days, bland diet',
                'subjective' => 'Epigastric pain and nausea after skipped meals for 3 days',
                'objectives' => 'Soft abdomen, epigastric tenderness, no rebound',
                'diagnostics' => 'Clinical diagnosis',
                'assessment' => 'Acute gastritis, likely stress-related',
                'plan' => 'PPI, avoid spicy food and NSAIDs, follow up if vomiting persists',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
            [
                'module_type' => 'health',
                'patient_type_id' => '1',
                'student_id' => '2024-ED-0211',
                'full_name' => 'Bianca Marie Lopez',
                'gender' => 'Female',
                'age' => 19,
                'marital_status' => 'Single',
                'religion' => 'Roman Catholic',
                'is_minor' => 'No',
                'phone_number' => '09271234501',
                'address' => 'Brgy. Irawan, Puerto Princesa City, Palawan',
                'department_id' => '6',
                'visit_date' => '2026-03-17',
                'case_type_id' => '7',
                'diagnosis' => 'Primary dysmenorrhea',
                'treatment' => 'Mefenamic acid 500mg TID for 3 days, warm compress',
                'subjective' => 'Severe lower abdominal cramps on day 1 of menses',
                'objectives' => 'Afebrile, soft abdomen, no adnexal tenderness',
                'diagnostics' => 'Clinical diagnosis',
                'assessment' => 'Primary dysmenorrhea',
                'plan' => 'NSAIDs at onset of pain, rest, return if pain is unrelieved',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
            [
                'module_type' => 'health',
                'patient_type_id' => '2',
                'student_id' => 'FAC-2018-004',
                'full_name' => 'Elena Grace Tan',
                'gender' => 'Female',
                'age' => 38,
                'marital_status' => 'Married',
                'religion' => 'Born Again Christian',
                'is_minor' => 'No',
                'phone_number' => '09175551234',
                'address' => 'Brgy. Sta. Monica, Puerto Princesa City, Palawan',
                'department_id' => '5',
                'visit_date' => '2026-03-21',
                'case_type_id' => '11',
                'diagnosis' => 'Migraine without aura',
                'treatment' => 'Paracetamol 500mg + rest in a dark room; advise trigger diary',
                'subjective' => 'Throbbing left-sided headache with photophobia since last night',
                'objectives' => 'BP 118/76, neurologic exam intact, no nuchal rigidity',
                'diagnostics' => 'Clinical diagnosis',
                'assessment' => 'Migraine without aura',
                'plan' => 'Analgesia, hydration, follow up if headaches become more frequent',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
            [
                'module_type' => 'health',
                'patient_type_id' => '1',
                'student_id' => '2022-AGRI-0067',
                'full_name' => 'Ryan Joseph Dela Pena',
                'gender' => 'Male',
                'age' => 22,
                'marital_status' => 'Single',
                'religion' => 'Iglesia ni Cristo',
                'is_minor' => 'No',
                'phone_number' => '09351237890',
                'address' => 'Brgy. Tagumpay, Puerto Princesa City, Palawan',
                'department_id' => '3',
                'visit_date' => '2026-03-26',
                'case_type_id' => '17',
                'diagnosis' => 'Left ankle sprain, grade I',
                'treatment' => 'RICE protocol, celecoxib 200mg once daily for 5 days, elastic bandage',
                'subjective' => 'Twisted left ankle during intramurals this morning',
                'objectives' => 'Mild swelling, no deformity, able to bear weight with limp',
                'diagnostics' => 'Clinical diagnosis; X-ray if no improvement in 48 hours',
                'assessment' => 'Grade I ankle sprain, non-work related',
                'plan' => 'Rest 3 days, no running, return if swelling or pain worsens',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
            [
                'module_type' => 'dental',
                'patient_type_id' => '1',
                'student_id' => '2023-FISH-0154',
                'full_name' => 'Christine Joy Abad',
                'gender' => 'Female',
                'age' => 20,
                'marital_status' => 'Single',
                'religion' => 'Roman Catholic',
                'is_minor' => 'No',
                'phone_number' => '09451236789',
                'address' => 'Brgy. Mandaragat, Puerto Princesa City, Palawan',
                'department_id' => '4',
                'visit_date' => '2026-03-27',
                'case_type_id' => '22',
                'diagnosis' => 'Dental caries, tooth #36',
                'treatment' => 'Oral hygiene instruction; referred for restoration',
                'subjective' => 'Toothache on lower left molar when drinking cold water',
                'objectives' => 'Visible occlusal caries on #36, no swelling, no lymphadenopathy',
                'diagnostics' => 'Clinical oral examination',
                'assessment' => 'Reversible pulpitis secondary to dental caries',
                'plan' => 'Dental restoration, advise fluoride toothpaste BID',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
            [
                'module_type' => 'health',
                'patient_type_id' => '3',
                'student_id' => 'STF-2015-012',
                'full_name' => 'Victor Hugo Salazar',
                'gender' => 'Male',
                'age' => 44,
                'marital_status' => 'Married',
                'religion' => 'Roman Catholic',
                'is_minor' => 'No',
                'phone_number' => '09190004567',
                'address' => 'Brgy. San Jose, Puerto Princesa City, Palawan',
                'department_id' => '1',
                'visit_date' => '2026-03-30',
                'case_type_id' => '2',
                'diagnosis' => 'Essential hypertension, uncontrolled',
                'treatment' => 'Amlodipine 5mg once daily, low-salt diet counseling',
                'subjective' => 'Occasional headache and nape pain for 1 week',
                'objectives' => 'BP 152/96 mmHg, HR 84, no edema',
                'diagnostics' => 'Clinic BP monitoring',
                'assessment' => 'Uncontrolled hypertension',
                'plan' => 'Start antihypertensive, home BP diary, follow up in 2 weeks',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
            [
                'module_type' => 'dental',
                'patient_type_id' => '1',
                'student_id' => '2025-ED-0033',
                'full_name' => 'Nicole Anne Flores',
                'gender' => 'Female',
                'age' => 18,
                'marital_status' => 'Single',
                'religion' => 'Roman Catholic',
                'is_minor' => 'No',
                'phone_number' => '09561230011',
                'address' => 'Brgy. San Manuel, Puerto Princesa City, Palawan',
                'department_id' => '6',
                'visit_date' => '2026-04-03',
                'case_type_id' => '22',
                'diagnosis' => 'Impacted mandibular third molar, tooth #38',
                'treatment' => 'Mefenamic acid 500mg TID PRN; referred for extraction',
                'subjective' => 'Pain and swelling at the back of the lower left jaw for 4 days',
                'objectives' => 'Pericoronitis around #38, limited mouth opening, no fever',
                'diagnostics' => 'Clinical oral examination',
                'assessment' => 'Pericoronitis due to partially erupted wisdom tooth',
                'plan' => 'Analgesia, warm saline rinses, dental extraction referral',
                'doctor' => 'Dr. Ana Patricia Cruz',
            ],
        ];
    }
}
